version: '3.4'
services:
  super-app-db:
    image: postgres
    environment:
      POSTGRES_DB: 'notesdb'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
    ports:
      - '5432:5432'
    expose:
      - '5432'

  counter-image:
    build: ./
    ports:
    - "8080:80"